### ISSUE TITLE
Failed to create SPIFFS image for partition storage

### ISSUE THREAD

**Issue by guideon** [pixma/esp32_wifi_ble_coexist_template#1]
Hi I have cloned your repository under vscode and tried to build it and got an error mentioned above.
I am using a Xiao ESP32S3 with a macbook air ventura 13.4.1 and vscode.
Your example is very good, as I am starting with the ESP-IDF i am not aware of all possible configs.
Here is the error message
618/894] Building C object esp...lient.dir/esp_http_client.c.objninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /Users/guyfauquembergue/esp32_wifi_ble_coexist_template/build/log/idf_py_stderr_output_6275 and /Users/guyfauquembergue/esp32_wifi_ble_coexist_template/build/log/idf_py_stdout_output_6275
Thanks in advance for your help. Guy

**Comment by pixma** [comment]
Hello,

I suspect that the flash size configuration which was there in is for WROOM32 module i.e. 4MB and the partition csv for it could be the thing which may be hindering to get it compiled.

- I have uploaded a new branch dev_S3 which has basic 8MB partition.
- Updated readme : Specially do "Device Configuration" -> ..... ->Select SoC to S3 module related variant of your interest.
- This will set the S3 SoC in sdkconfig.
- Provided a few links for conveniently mapping your own partitions based on the size of flash at your disposal.


If the issue still persist, please post more details of your output, for example that _stdout_output_NNNN file contains more details about what went wrong while building.

I suspect that the http client library was the point where the flash area code ram out of flash space (factory area) based on partition information supplied or mentioned in csv which make this build fail.

PS: I do not have the Xiao ESP32S3, nor I have tested this push : but the dev_s3 got build for S3 variant for 8MB flash size. 

Regards,

**Comment by guideon** [comment]
Thanks Annim, I'l make additional trial, for the time being I am getting issues with my macbook air M1. Building with cmake is not so easy so once I'l be ok with this I'll do some other test. Regards Guy.
